// This file is generated from resources/js/generated/generated.d.ts.
// Run `ddev artisan typescript:generate-types` or `ddev composer typescript`
// to refresh.

// Do not edit this file directly.
// -------------------------------

// App.Data

// App.Data.Auth
export type CreateTokenData = App.Data.Auth.CreateTokenData;
export type RegisterData = App.Data.Auth.RegisterData;
export type RevokeTokenData = App.Data.Auth.RevokeTokenData;
export type TokenData = App.Data.Auth.TokenData;
export type UserData = App.Data.Auth.UserData;

// App.Data.Blog

// App.Data.Blog.Requests
export type StoreCommentData = App.Data.Blog.Requests.StoreCommentData;
export type StorePostData = App.Data.Blog.Requests.StorePostData;
export type UpdateCommentData = App.Data.Blog.Requests.UpdateCommentData;
export type UpdatePostData = App.Data.Blog.Requests.UpdatePostData;

// App.Data.Blog.Responses
export type CommentData = App.Data.Blog.Responses.CommentData;
export type PostData = App.Data.Blog.Responses.PostData;
export type PostForCommentData = App.Data.Blog.Responses.PostForCommentData;

// App.Enums
export type RoleLabel = App.Enums.RoleLabel;
